# Single source of truth for supported languages (full names)
languages = [
    'English',        # en
    'Spanish',        # es
    'French',         # fr
    'German',         # de
    'Italian',        # it
    'Portuguese',     # pt
    'Russian',        # ru
    'Japanese',       # ja
    'Korean',         # ko
    'Arabic',         # ar
    'Chinese',        # zh
    'Hindi',          # hi
    'Bengali',        # bn
    'Punjabi',        # pa
    'Vietnamese',     # vi
    'Indonesian',     # id
    'Turkish',        # tr
    'Persian',        # fa
    'Tamil',          # ta
    'Telugu',         # te
    'Marathi',        # mr
    'Urdu',           # ur
    'Swahili',        # sw
    'Thai',           # th
    'Malay',          # ms
    'Gujarati',       # gu
    'Kannada',        # kn
    'Malayalam',      # ml
    'Odia',           # or
    'Sinhala',        # si
    'Pashto'          # ps
]



language_codes = [
    'en',  # English
    'es',  # Spanish
    'fr',  # French
    'de',  # German
    'it',  # Italian
    'pt',  # Portuguese
    'ru',  # Russian
    'ja',  # Japanese
    'ko',  # Korean
    'ar',  # Arabic
    'zh',  # Chinese
    'hi',  # Hindi
    'bn',  # Bengali
    'pa',  # Punjabi
    'vi',  # Vietnamese
    'id',  # Indonesian
    'tr',  # Turkish
    'fa',  # Persian
    'ta',  # Tamil
    'te',  # Telugu
    'mr',  # Marathi
    'ur',  # Urdu
    'sw',  # Swahili
    'th',  # Thai
    'ms',  # Malay
    'gu',  # Gujarati
    'kn',  # Kannada
    'ml',  # Malayalam
    'or',  # Odia
    'si',  # Sinhala
    'ps'   # Pashto
]
